  function setDebugFlags(debug, cont) { showdebug=!!debug; continuous=!!cont; }

  return {
    initialize: initialize,
    start: start,
    setDebugFlags: setDebugFlags,
    getContext: getContext,
    getPointerRadius: getPointerRadius,
    isMouseEnabled: isMouseEnabled,
    View: View,
    ViewDivider: ViewDivider,
    ViewOverlay: ViewOverlay,
    ViewMultiverse: ViewMultiverse,
    ViewPicker: ViewPicker,
    Gadget: Gadget,
    MatrixGadget: MatrixGadget,
    SwipeGadget: SwipeGadget,
    MiddleDividerGadget: MiddleDividerGadget,
    GAF_CLICKABLE: GAF_CLICKABLE,
    GAF_CONTEXTMENU: GAF_CONTEXTMENU,
    GAF_STRETCHABLE: GAF_STRETCHABLE,
    GAF_DRAGGABLE_UPDOWN: GAF_DRAGGABLE_UPDOWN,
    GAF_DRAGGABLE_LEFTRIGHT: GAF_DRAGGABLE_LEFTRIGHT,
    GAF_DRAGGABLE: GAF_DRAGGABLE,
    GAF_SWIPEABLE_UPDOWN: GAF_SWIPEABLE_UPDOWN,
    GAF_SWIPEABLE_LEFTRIGHT: GAF_SWIPEABLE_LEFTRIGHT,
    GAF_SWIPEABLE: GAF_SWIPEABLE,
    GAF_SCROLLABLE_UPDOWN: GAF_SCROLLABLE_UPDOWN,
    GAF_SCROLLABLE_LEFTRIGHT: GAF_SCROLLABLE_LEFTRIGHT,
    GAF_SCROLLABLE: GAF_SCROLLABLE,
    GAF_SCALABLE: GAF_SCALABLE,
    GAF_ROTATABLE: GAF_ROTATABLE,
    GAF_PINCHABLE: GAF_PINCHABLE,
    GAF_ALL: GAF_ALL,
    HitList: HitList,
    LayoutState: LayoutState,
  };
})();
