  function setDebugFlags(debug, cont) { showdebug=!!debug; continuous=!!cont; }
  function beep() {
		if (beepSound) beepSound.setValueAtTime(1, ac.currentTime);
		if (beepSound) beepSound.setValueAtTime(0, ac.currentTime+0.1);
	};

  return {
    initialize: initialize,
    start: start,
    setDebugFlags: setDebugFlags,
    getContext: getContext,
    getPointerRadius: getPointerRadius,
    isMouseEnabled: isMouseEnabled,
		getInputGad: getInputGad,
		beginInput: beginInput,
		endInput: endInput,
		beep: beep,
    View: View,
    DividerView: DividerView,
    SliceView: SliceView,
    PagesView: PagesView,
		PopupView: PopupView,
    ViewOverlay: ViewOverlay,
    ViewMultiverse: ViewMultiverse,
    ViewPicker: ViewPicker,
    Gadget: Gadget,
    MatrixGadget: MatrixGadget,
    SwipeGadget: SwipeGadget,
    MiddleDividerGadget: MiddleDividerGadget,
    GAF_CLICKABLE: GAF_CLICKABLE,
    GAF_HOLDABLE: GAF_HOLDABLE,
    GAF_CONTEXTMENU: GAF_CONTEXTMENU,
    GAF_STRETCHABLE: GAF_STRETCHABLE,
    GAF_DRAGGABLE_UPDOWN: GAF_DRAGGABLE_UPDOWN,
    GAF_DRAGGABLE_LEFTRIGHT: GAF_DRAGGABLE_LEFTRIGHT,
    GAF_DRAGGABLE: GAF_DRAGGABLE,
    GAF_SWIPEABLE_UPDOWN: GAF_SWIPEABLE_UPDOWN,
    GAF_SWIPEABLE_LEFTRIGHT: GAF_SWIPEABLE_LEFTRIGHT,
    GAF_SWIPEABLE: GAF_SWIPEABLE,
    GAF_SCROLLABLE_UPDOWN: GAF_SCROLLABLE_UPDOWN,
    GAF_SCROLLABLE_LEFTRIGHT: GAF_SCROLLABLE_LEFTRIGHT,
    GAF_SCROLLABLE: GAF_SCROLLABLE,
    GAF_SCALABLE: GAF_SCALABLE,
    GAF_ROTATABLE: GAF_ROTATABLE,
    GAF_PINCHABLE: GAF_PINCHABLE,
    GAF_NUMINPUT: GAF_NUMINPUT,
    GAF_TEXTINPUT: GAF_TEXTINPUT,
		GAF_GONEXT: GAF_GONEXT,
    GAF_ALL: GAF_ALL,
    HitList: HitList,
    LayoutState: LayoutState,
  };
})();
